# Generated by Django 3.2 on 2021-05-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPEModel',
            fields=[
                ('cpeId', models.AutoField(db_column='cpe_id', primary_key=True, serialize=False, unique=True)),
                ('serieCpe', models.CharField(db_column='cpe_serie', max_length=4)),
                ('numeroCpe', models.CharField(db_column='cpe_numero', max_length=8)),
                ('fechaCpe', models.DateField(db_column='cpe_fecha')),
                ('fechavencCpe', models.DateField(db_column='cpe_fechavenc')),
                ('totalCpe', models.DecimalField(db_column='cpe_total', decimal_places=2, max_digits=14)),
                ('fechapublicacionCpe', models.DateTimeField(db_column='cpe_fechapublicacion')),
                ('monedaCpe', models.CharField(db_column='cpe_moneda', max_length=8, null=True)),
                ('serierefCpe', models.CharField(db_column='cpe_serieref', max_length=4, null=True)),
                ('numerorefCpe', models.CharField(db_column='cpe_numeroref', max_length=8, null=True)),
                ('fecharefCpe', models.DateField(db_column='cpe_fecharef', null=True)),
                ('XmlCpe', models.TextField(db_column='cpe_xml')),
                ('CdrCpe', models.TextField(db_column='cpe_cdr', null=True)),
                ('PdfCpe', models.TextField(db_column='cpe_pdf', null=True)),
                ('idCdr', models.CharField(db_column='cdr_id', max_length=20)),
                ('fechaCdr', models.DateField(db_column='cdr_fecha', null=True)),
                ('horaCdr', models.CharField(db_column='cdr_hora', max_length=10, null=True)),
                ('statusCdr', models.CharField(db_column='cdr_status', max_length=5, null=True)),
                ('mensajeCdr', models.TextField(db_column='cdr_mensaje', null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 't_cpe',
            },
        ),
        migrations.CreateModel(
            name='EmisorModel',
            fields=[
                ('emisorId', models.AutoField(db_column='emisor_id', primary_key=True, serialize=False, unique=True)),
                ('emisorNroDoc', models.CharField(db_column='emisor_nrodoc', max_length=20)),
                ('emisorRazonSocial', models.CharField(db_column='emisor_razonsocial', max_length=100)),
                ('emisorUsuarioSunat', models.CharField(db_column='emisor_usuariosunat', max_length=20)),
                ('emisorClaveSunat', models.CharField(db_column='emisor_clavesunat', max_length=20)),
                ('emisorClave', models.CharField(db_column='emisor_clave', max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_emisor',
            },
        ),
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('estadoId', models.AutoField(db_column='estado_id', primary_key=True, serialize=False, unique=True)),
                ('estadoDesc', models.CharField(db_column='estado_desc', max_length=30)),
                ('estadoCod', models.CharField(db_column='estado_cod', max_length=3)),
                ('estadoTipo', models.CharField(db_column='estado_tipo', max_length=3)),
                ('estadoCond', models.CharField(db_column='estado_cond', max_length=3)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_estado',
            },
        ),
        migrations.CreateModel(
            name='SucursalModel',
            fields=[
                ('sucursalId', models.AutoField(db_column='sucursal_id', primary_key=True, serialize=False, unique=True)),
                ('sucursalDesc', models.CharField(db_column='sucursal_desc', max_length=50)),
                ('sucursalCod', models.CharField(db_column='sucursal_cod', max_length=3)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_sucursal',
            },
        ),
        migrations.CreateModel(
            name='TipoCPEModel',
            fields=[
                ('tipocpeId', models.AutoField(db_column='tipocpe_id', primary_key=True, serialize=False, unique=True)),
                ('tipocpeDesc', models.CharField(db_column='tipocpe_desc', max_length=50)),
                ('tipocpeCod', models.CharField(db_column='tipocpe_cod', max_length=3)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_tipocpe',
            },
        ),
        migrations.CreateModel(
            name='TipoDOCModel',
            fields=[
                ('tipodocId', models.AutoField(db_column='tipodoc_id', primary_key=True, serialize=False, unique=True)),
                ('tipodocDesc', models.CharField(db_column='tipodoc_desc', max_length=50)),
                ('tipodocCod', models.CharField(db_column='tipodoc_cod', max_length=3)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_tipodoc',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('usuId', models.AutoField(db_column='usu_id', primary_key=True, serialize=False, unique=True)),
                ('usuCorreo', models.EmailField(db_column='usu_correo', max_length=254, unique=True)),
                ('usuNombre', models.CharField(db_column='usu_nombre', max_length=50, null=True)),
                ('usuCel', models.CharField(db_column='usu_cel', default='', max_length=13)),
                ('password', models.TextField(db_column='usu_pass')),
            ],
            options={
                'db_table': 't_usuario',
            },
        ),
        migrations.CreateModel(
            name='ResumenModel',
            fields=[
                ('resumenId', models.AutoField(db_column='resumen_id', primary_key=True, serialize=False, unique=True)),
                ('ID', models.CharField(db_column='ID', max_length=20)),
                ('fechaemisionresumen', models.DateField(db_column='resumen_fechaemision')),
                ('fechageneracionresumen', models.DateField(db_column='resumen_fechageneracion')),
                ('fechapublicacionresumen', models.DateTimeField(db_column='resumen_fechapublicacion')),
                ('ticketresumen', models.CharField(db_column='resumen_ticket', max_length=20)),
                ('XmlCpe', models.TextField(db_column='resumen_xml')),
                ('CdrCpe', models.TextField(db_column='resumen_cdr', null=True)),
                ('PdfCpe', models.TextField(db_column='resumen_pdf', null=True)),
                ('idCdr', models.CharField(db_column='cdr_id', max_length=20)),
                ('fechaCdr', models.DateField(db_column='cdr_fecha', null=True)),
                ('horaCdr', models.CharField(db_column='cdr_hora', max_length=10, null=True)),
                ('statusCdr', models.CharField(db_column='cdr_status', max_length=5, null=True)),
                ('mensajeCdr', models.TextField(db_column='cdr_mensaje', null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('emisorId', models.ForeignKey(db_column='emisor_id', on_delete=django.db.models.deletion.PROTECT, to='register.emisormodel')),
                ('estadoId', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='register.estadomodel')),
                ('tipocpeId', models.ForeignKey(db_column='tipocpe_id', on_delete=django.db.models.deletion.PROTECT, to='register.tipocpemodel')),
                ('usuId', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioResumen', to='register.usuariomodel')),
            ],
            options={
                'db_table': 't_resumen',
            },
        ),
        migrations.CreateModel(
            name='ReceptorModel',
            fields=[
                ('receptorId', models.AutoField(db_column='receptor_id', primary_key=True, serialize=False, unique=True)),
                ('receptorNroDoc', models.CharField(db_column='receptor_nrodoc', max_length=20)),
                ('receptorRazonSocial', models.CharField(db_column='receptor_razonsocial', max_length=100)),
                ('tipodocId', models.ForeignKey(db_column='tipodoc_id', on_delete=django.db.models.deletion.PROTECT, to='register.tipodocmodel')),
            ],
            options={
                'db_table': 't_receptor',
            },
        ),
        migrations.CreateModel(
            name='EventosResumenModel',
            fields=[
                ('eventosresumenId', models.AutoField(db_column='eventosresumen_id', primary_key=True, serialize=False, unique=True)),
                ('descripcionEventosCpe', models.CharField(db_column='eventoscpe_descripcion', max_length=100)),
                ('observacionEventosCpe', models.CharField(db_column='eventoscpe_observacion', max_length=2000)),
                ('fechaEventosCpe', models.CharField(db_column='eventoscpe_fecha', max_length=100)),
                ('resumenId', models.ForeignKey(db_column='resumen_id', on_delete=django.db.models.deletion.PROTECT, to='register.resumenmodel')),
            ],
            options={
                'db_table': 't_eventosresumen',
            },
        ),
        migrations.CreateModel(
            name='EventosCPEModel',
            fields=[
                ('eventoscpeId', models.AutoField(db_column='eventoscpe_id', primary_key=True, serialize=False, unique=True)),
                ('descripcionEventosCpe', models.CharField(db_column='eventoscpe_descripcion', max_length=100)),
                ('observacionEventosCpe', models.CharField(db_column='eventoscpe_observacion', max_length=2000)),
                ('fechaEventosCpe', models.CharField(db_column='eventoscpe_fecha', max_length=100)),
                ('cpeId', models.ForeignKey(db_column='cpe_id', on_delete=django.db.models.deletion.PROTECT, to='register.cpemodel')),
            ],
            options={
                'db_table': 't_eventoscpe',
            },
        ),
        migrations.CreateModel(
            name='EmisorUsuarioModel',
            fields=[
                ('emisorusuarioId', models.AutoField(db_column='emisorusuario_id', primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('emisorId', models.ForeignKey(db_column='emisor_id', on_delete=django.db.models.deletion.PROTECT, to='register.emisormodel')),
                ('usuId', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioEmisor', to='register.usuariomodel')),
            ],
            options={
                'db_table': 't_emisorusuario',
            },
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='emisorId',
            field=models.ForeignKey(db_column='emisor_id', on_delete=django.db.models.deletion.PROTECT, to='register.emisormodel'),
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='estadoId',
            field=models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='register.estadomodel'),
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='receptorId',
            field=models.ForeignKey(db_column='receptor_id', on_delete=django.db.models.deletion.PROTECT, to='register.receptormodel'),
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='sucursalId',
            field=models.ForeignKey(db_column='sucursal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='register.sucursalmodel'),
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='tipocpeId',
            field=models.ForeignKey(db_column='tipocpe_id', on_delete=django.db.models.deletion.PROTECT, related_name='TipoCpeCpe', to='register.tipocpemodel'),
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='tipocperefId',
            field=models.ForeignKey(db_column='tipocperef_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='register.tipocpemodel'),
        ),
        migrations.AddField(
            model_name='cpemodel',
            name='usuId',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioCpe', to='register.usuariomodel'),
        ),
    ]
