# Generated by Django 3.2 on 2021-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpemodel',
            name='importeCpe',
            field=models.DecimalField(db_column='cpe_immporte', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='XmlCpe',
            field=models.TextField(db_column='cpe_xml', null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='fechaCpe',
            field=models.DateField(db_column='cpe_fecha', null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='fechapublicacionCpe',
            field=models.DateTimeField(db_column='cpe_fechapublicacion', null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='fechavencCpe',
            field=models.DateField(db_column='cpe_fechavenc', null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='idCdr',
            field=models.CharField(db_column='cdr_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='numeroCpe',
            field=models.CharField(db_column='cpe_numero', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='serieCpe',
            field=models.CharField(db_column='cpe_serie', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cpemodel',
            name='totalCpe',
            field=models.DecimalField(db_column='cpe_total', decimal_places=2, max_digits=14, null=True),
        ),
    ]
