# Generated by Django 3.2 on 2021-12-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211204_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPEResumenModel',
            fields=[
                ('cperesumenId', models.AutoField(db_column='cperesumen_id', primary_key=True, serialize=False, unique=True)),
                ('serierefCpe', models.CharField(db_column='cperesumen_serieref', max_length=4, null=True)),
                ('numerorefCpe', models.CharField(db_column='cperesumen_numeroref', max_length=8, null=True)),
                ('resumenId', models.ForeignKey(db_column='resumen_id', on_delete=django.db.models.deletion.PROTECT, to='register.resumenmodel')),
                ('tipocperefId', models.ForeignKey(db_column='tipocperef_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='register.tipocpemodel')),
            ],
            options={
                'db_table': 't_cperesumen',
            },
        ),
    ]
